"""enforcing 1-to-1 relationship with patients and medical/dental records

Revision ID: 1708d943880e
Revises: 80a71184b177
Create Date: 2026-03-11 16:59:58.501995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1708d943880e'
down_revision: Union[str, Sequence[str], None] = '80a71184b177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentalrecordupdate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalrecordupdate_dr_uuid'), ['dr_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentalrecordupdate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalrecordupdate_dr_uuid'))

    # ### end Alembic commands ###
