"""refactor: drop PatientSmokingTypes and SmokingTypesLookup and simplify smoking schema

Revision ID: 194f59abbc47
Revises: 38ffdbd4e577
Create Date: 2026-03-12 02:03:50.841674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '194f59abbc47'
down_revision: Union[str, Sequence[str], None] = '38ffdbd4e577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicalexamination', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalexamination_me_id'))
        batch_op.drop_index(batch_op.f('ix_medicalexamination_patient_uuid'))
        batch_op.drop_index(batch_op.f('ix_medicalexamination_uuid'))

    op.drop_table('medicalexamination')
    with op.batch_alter_table('medicalhistorysnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalhistorysnapshot_original_mh_uuid'))
        batch_op.drop_index(batch_op.f('ix_medicalhistorysnapshot_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_medicalhistorysnapshot_uuid'))

    op.drop_table('medicalhistorysnapshot')
    with op.batch_alter_table('patientfamilyhistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patientfamilyhistory_pfh_id'))
        batch_op.drop_index(batch_op.f('ix_patientfamilyhistory_uuid'))

    op.drop_table('patientfamilyhistory')
    with op.batch_alter_table('personneltype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personneltype_personnel_id'))
        batch_op.drop_index(batch_op.f('ix_personneltype_uuid'))

    op.drop_table('personneltype')
    with op.batch_alter_table('dentalrecordsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalrecordsnapshot_original_dr_uuid'))
        batch_op.drop_index(batch_op.f('ix_dentalrecordsnapshot_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_dentalrecordsnapshot_uuid'))

    op.drop_table('dentalrecordsnapshot')
    with op.batch_alter_table('patientsmokingtypes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patientsmokingtypes_uuid'))

    op.drop_table('patientsmokingtypes')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_uuid'))

    op.drop_table('user')
    with op.batch_alter_table('medicalhistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalhistory_mh_id'))
        batch_op.drop_index(batch_op.f('ix_medicalhistory_patient_uuid'))
        batch_op.drop_index(batch_op.f('ix_medicalhistory_uuid'))

    op.drop_table('medicalhistory')
    with op.batch_alter_table('toothfinding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_toothfinding_tf_id'))
        batch_op.drop_index(batch_op.f('ix_toothfinding_uuid'))

    op.drop_table('toothfinding')
    with op.batch_alter_table('dentalrecordupdate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalrecordupdate_dr_uuid'))
        batch_op.drop_index(batch_op.f('ix_dentalrecordupdate_dru_id'))
        batch_op.drop_index(batch_op.f('ix_dentalrecordupdate_uuid'))

    op.drop_table('dentalrecordupdate')
    with op.batch_alter_table('clinictransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinictransaction_ct_id'))
        batch_op.drop_index(batch_op.f('ix_clinictransaction_patient_uuid'))
        batch_op.drop_index(batch_op.f('ix_clinictransaction_uuid'))

    op.drop_table('clinictransaction')
    with op.batch_alter_table('studenttype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studenttype_student_id'))
        batch_op.drop_index(batch_op.f('ix_studenttype_uuid'))

    op.drop_table('studenttype')
    with op.batch_alter_table('bodysystemslookup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bodysystemslookup_bsl_id'))
        batch_op.drop_index(batch_op.f('ix_bodysystemslookup_uuid'))

    op.drop_table('bodysystemslookup')
    with op.batch_alter_table('departmentslookup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departmentslookup_department_type'))
        batch_op.drop_index(batch_op.f('ix_departmentslookup_dl_id'))
        batch_op.drop_index(batch_op.f('ix_departmentslookup_uuid'))

    op.drop_table('departmentslookup')
    with op.batch_alter_table('dentalservicerendered', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalservicerendered_dsr_id'))
        batch_op.drop_index(batch_op.f('ix_dentalservicerendered_uuid'))

    op.drop_table('dentalservicerendered')
    with op.batch_alter_table('dentalexaminationsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalexaminationsnapshot_original_dr_uuid'))
        batch_op.drop_index(batch_op.f('ix_dentalexaminationsnapshot_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_dentalexaminationsnapshot_uuid'))

    op.drop_table('dentalexaminationsnapshot')
    with op.batch_alter_table('medicalconditionslookup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalconditionslookup_mcl_id'))
        batch_op.drop_index(batch_op.f('ix_medicalconditionslookup_uuid'))

    op.drop_table('medicalconditionslookup')
    with op.batch_alter_table('vitalsigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vitalsigns_ct_uuid'))
        batch_op.drop_index(batch_op.f('ix_vitalsigns_uuid'))
        batch_op.drop_index(batch_op.f('ix_vitalsigns_vs_id'))

    op.drop_table('vitalsigns')
    with op.batch_alter_table('medicalexaminationsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalexaminationsnapshot_original_me_uuid'))
        batch_op.drop_index(batch_op.f('ix_medicalexaminationsnapshot_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_medicalexaminationsnapshot_uuid'))

    op.drop_table('medicalexaminationsnapshot')
    with op.batch_alter_table('medicaltreatment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicaltreatment_mt_id'))
        batch_op.drop_index(batch_op.f('ix_medicaltreatment_uuid'))

    op.drop_table('medicaltreatment')
    with op.batch_alter_table('medicalexaminationfindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalexaminationfindings_uuid'))

    op.drop_table('medicalexaminationfindings')
    with op.batch_alter_table('emergencycontact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergencycontact_ec_id'))
        batch_op.drop_index(batch_op.f('ix_emergencycontact_uuid'))

    op.drop_table('emergencycontact')
    with op.batch_alter_table('dentalrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalrecord_dr_id'))
        batch_op.drop_index(batch_op.f('ix_dentalrecord_patient_uuid'))
        batch_op.drop_index(batch_op.f('ix_dentalrecord_uuid'))

    op.drop_table('dentalrecord')
    with op.batch_alter_table('patientinformation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patientinformation_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patientinformation_patient_type'))
        batch_op.drop_index(batch_op.f('ix_patientinformation_uuid'))

    op.drop_table('patientinformation')
    with op.batch_alter_table('patientdiagnosedconditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patientdiagnosedconditions_uuid'))

    op.drop_table('patientdiagnosedconditions')
    with op.batch_alter_table('smokingtypeslookup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smokingtypeslookup_stl_id'))
        batch_op.drop_index(batch_op.f('ix_smokingtypeslookup_uuid'))

    op.drop_table('smokingtypeslookup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smokingtypeslookup',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('stl_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('type_name')
    )
    with op.batch_alter_table('smokingtypeslookup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smokingtypeslookup_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_smokingtypeslookup_stl_id'), ['stl_id'], unique=1)

    op.create_table('patientdiagnosedconditions',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mh_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mcl_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('date_diagnosed', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['mcl_uuid'], ['medicalconditionslookup.uuid'], ),
    sa.ForeignKeyConstraint(['mh_uuid'], ['medicalhistory.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('patientdiagnosedconditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patientdiagnosedconditions_uuid'), ['uuid'], unique=False)

    op.create_table('patientinformation',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_type', sa.VARCHAR(length=9), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('birthdate', sa.DATE(), nullable=False),
    sa.Column('sex', sa.VARCHAR(length=1), nullable=False),
    sa.Column('civil_status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('religion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact_no', sa.VARCHAR(length=50), nullable=True),
    sa.Column('house_no', sa.VARCHAR(length=20), nullable=True),
    sa.Column('street', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subdivision', sa.VARCHAR(length=100), nullable=True),
    sa.Column('barangay', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('province', sa.VARCHAR(length=100), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('patientinformation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patientinformation_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_patientinformation_patient_type'), ['patient_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_patientinformation_patient_id'), ['patient_id'], unique=1)

    op.create_table('dentalrecord',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('dr_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mh_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('last_dental_visit', sa.DATE(), nullable=True),
    sa.Column('reason_for_last_dental_visit', sa.TEXT(), nullable=True),
    sa.Column('last_hospitalization', sa.DATE(), nullable=True),
    sa.Column('hospitalization_reason', sa.TEXT(), nullable=True),
    sa.Column('known_allergies', sa.TEXT(), nullable=True),
    sa.Column('tobacco_use', sa.TEXT(), nullable=True),
    sa.Column('alcohol_drug_use', sa.TEXT(), nullable=True),
    sa.Column('for_women_status', sa.TEXT(), nullable=True),
    sa.Column('chart_image_url', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['mh_uuid'], ['medicalhistory.uuid'], ),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patientinformation.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('dentalrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalrecord_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentalrecord_patient_uuid'), ['patient_uuid'], unique=1)
        batch_op.create_index(batch_op.f('ix_dentalrecord_dr_id'), ['dr_id'], unique=1)

    op.create_table('emergencycontact',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('ec_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('relation_to_patient', sa.VARCHAR(length=100), nullable=False),
    sa.Column('house_no', sa.VARCHAR(length=20), nullable=True),
    sa.Column('street', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subdivision', sa.VARCHAR(length=100), nullable=True),
    sa.Column('barangay', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('province', sa.VARCHAR(length=100), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patientinformation.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('patient_uuid', name=op.f('uq_emergencycontact_patient_uuid'))
    )
    with op.batch_alter_table('emergencycontact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergencycontact_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergencycontact_ec_id'), ['ec_id'], unique=1)

    op.create_table('medicalexaminationfindings',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('me_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('bsl_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=12), nullable=False),
    sa.Column('condition_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['bsl_uuid'], ['bodysystemslookup.uuid'], ),
    sa.ForeignKeyConstraint(['me_uuid'], ['medicalexamination.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicalexaminationfindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalexaminationfindings_uuid'), ['uuid'], unique=False)

    op.create_table('medicaltreatment',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mt_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('mh_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('date_taken', sa.DATE(), nullable=False),
    sa.Column('physician_notes', sa.TEXT(), nullable=True),
    sa.Column('nurse_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['mh_uuid'], ['medicalhistory.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicaltreatment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicaltreatment_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicaltreatment_mt_id'), ['mt_id'], unique=1)

    op.create_table('medicalexaminationsnapshot',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('original_me_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('snapshot_date', sa.DATETIME(), nullable=False),
    sa.Column('date_taken', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['original_me_uuid'], ['medicalexamination.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicalexaminationsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalexaminationsnapshot_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicalexaminationsnapshot_snapshot_id'), ['snapshot_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_medicalexaminationsnapshot_original_me_uuid'), ['original_me_uuid'], unique=False)

    op.create_table('vitalsigns',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('vs_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('ct_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('date_taken', sa.DATE(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('bmi', sa.FLOAT(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('pulse', sa.INTEGER(), nullable=True),
    sa.Column('blood_pressure', sa.VARCHAR(length=10), nullable=True),
    sa.Column('respiratory_rate', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ct_uuid'], ['clinictransaction.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('vitalsigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vitalsigns_vs_id'), ['vs_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_vitalsigns_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_vitalsigns_ct_uuid'), ['ct_uuid'], unique=False)

    op.create_table('medicalconditionslookup',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mcl_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('condition_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('condition_name')
    )
    with op.batch_alter_table('medicalconditionslookup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalconditionslookup_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicalconditionslookup_mcl_id'), ['mcl_id'], unique=1)

    op.create_table('dentalexaminationsnapshot',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('original_dr_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('snapshot_date', sa.DATETIME(), nullable=False),
    sa.Column('examination_date', sa.DATE(), nullable=False),
    sa.Column('head_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('face_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tmj_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('periodontal_diagnosis', sa.VARCHAR(length=25), nullable=True),
    sa.Column('periodontitis_severity', sa.VARCHAR(length=8), nullable=True),
    sa.Column('periodontal_others', sa.TEXT(), nullable=True),
    sa.Column('lips_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('palate_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('floor_of_mouth_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tongue_findings', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['original_dr_uuid'], ['dentalrecordupdate.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('dentalexaminationsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalexaminationsnapshot_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentalexaminationsnapshot_snapshot_id'), ['snapshot_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_dentalexaminationsnapshot_original_dr_uuid'), ['original_dr_uuid'], unique=False)

    op.create_table('dentalservicerendered',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('dsr_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dr_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('service_date', sa.DATE(), nullable=False),
    sa.Column('tooth_number', sa.VARCHAR(length=5), nullable=True),
    sa.Column('oral_prophy', sa.BOOLEAN(), nullable=False),
    sa.Column('temp_filling', sa.BOOLEAN(), nullable=False),
    sa.Column('perm_filling', sa.BOOLEAN(), nullable=False),
    sa.Column('sealant', sa.BOOLEAN(), nullable=False),
    sa.Column('extraction', sa.BOOLEAN(), nullable=False),
    sa.Column('consultation', sa.BOOLEAN(), nullable=False),
    sa.Column('others', sa.TEXT(), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['dr_uuid'], ['dentalrecord.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('dentalservicerendered', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalservicerendered_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentalservicerendered_dsr_id'), ['dsr_id'], unique=1)

    op.create_table('departmentslookup',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('dl_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('department_type', sa.VARCHAR(length=14), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('department_name')
    )
    with op.batch_alter_table('departmentslookup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departmentslookup_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_departmentslookup_dl_id'), ['dl_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_departmentslookup_department_type'), ['department_type'], unique=False)

    op.create_table('bodysystemslookup',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('bsl_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('system_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('system_name')
    )
    with op.batch_alter_table('bodysystemslookup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bodysystemslookup_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_bodysystemslookup_bsl_id'), ['bsl_id'], unique=1)

    op.create_table('studenttype',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('patient_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dl_uuid', sa.CHAR(length=32), nullable=True),
    sa.Column('course', sa.VARCHAR(length=100), nullable=False),
    sa.Column('batch', sa.VARCHAR(length=20), nullable=False),
    sa.Column('school_year', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dl_uuid'], ['departmentslookup.uuid'], ),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patientinformation.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('patient_uuid')
    )
    with op.batch_alter_table('studenttype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studenttype_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_studenttype_student_id'), ['student_id'], unique=1)

    op.create_table('clinictransaction',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('ct_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('transaction_date', sa.DATE(), nullable=False),
    sa.Column('time_in', sa.TIME(), nullable=False),
    sa.Column('time_out', sa.TIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('medication_given', sa.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('remarks', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patientinformation.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('clinictransaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinictransaction_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinictransaction_patient_uuid'), ['patient_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinictransaction_ct_id'), ['ct_id'], unique=1)

    op.create_table('dentalrecordupdate',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('dru_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dr_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('examination_date', sa.DATE(), nullable=False),
    sa.Column('head_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('face_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tmj_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('periodontal_diagnosis', sa.VARCHAR(length=25), nullable=True),
    sa.Column('periodontitis_severity', sa.VARCHAR(length=8), nullable=True),
    sa.Column('periodontal_others', sa.TEXT(), nullable=True),
    sa.Column('lips_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('palate_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('floor_of_mouth_findings', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tongue_findings', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dr_uuid'], ['dentalrecord.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('dentalrecordupdate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalrecordupdate_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentalrecordupdate_dru_id'), ['dru_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_dentalrecordupdate_dr_uuid'), ['dr_uuid'], unique=1)

    op.create_table('toothfinding',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('tf_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dru_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('tooth_number', sa.VARCHAR(length=5), nullable=False),
    sa.Column('status', sa.VARCHAR(length=14), nullable=False),
    sa.ForeignKeyConstraint(['dru_uuid'], ['dentalrecordupdate.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('toothfinding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_toothfinding_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_toothfinding_tf_id'), ['tf_id'], unique=1)

    op.create_table('medicalhistory',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mh_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('smoking_status', sa.VARCHAR(length=13), nullable=False),
    sa.Column('smoking_started_since', sa.DATE(), nullable=True),
    sa.Column('drug_status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('drug_name', sa.VARCHAR(), nullable=True),
    sa.Column('did_rehab', sa.BOOLEAN(), nullable=True),
    sa.Column('alcohol_status', sa.VARCHAR(length=21), nullable=False),
    sa.Column('alcohol_est_consumption', sa.VARCHAR(), nullable=True),
    sa.Column('no_of_pregnancies', sa.INTEGER(), nullable=True),
    sa.Column('no_of_miscarriages', sa.INTEGER(), nullable=True),
    sa.Column('no_of_term_deliveries', sa.INTEGER(), nullable=True),
    sa.Column('no_of_premature_deliveries', sa.INTEGER(), nullable=True),
    sa.Column('total_children', sa.INTEGER(), nullable=True),
    sa.Column('surgery_notes', sa.TEXT(), nullable=True),
    sa.Column('maintenance_medications', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patientinformation.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicalhistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalhistory_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicalhistory_patient_uuid'), ['patient_uuid'], unique=1)
        batch_op.create_index(batch_op.f('ix_medicalhistory_mh_id'), ['mh_id'], unique=1)

    op.create_table('user',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_user_id'), ['user_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    op.create_table('patientsmokingtypes',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mh_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('stl_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('frequency', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['mh_uuid'], ['medicalhistory.uuid'], ),
    sa.ForeignKeyConstraint(['stl_uuid'], ['smokingtypeslookup.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('patientsmokingtypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patientsmokingtypes_uuid'), ['uuid'], unique=False)

    op.create_table('dentalrecordsnapshot',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('original_dr_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('snapshot_date', sa.DATETIME(), nullable=False),
    sa.Column('last_dental_visit', sa.DATE(), nullable=True),
    sa.Column('reason_for_last_dental_visit', sa.TEXT(), nullable=True),
    sa.Column('last_hospitalization', sa.DATE(), nullable=True),
    sa.Column('hospitalization_reason', sa.TEXT(), nullable=True),
    sa.Column('known_allergies', sa.TEXT(), nullable=True),
    sa.Column('tobacco_use', sa.TEXT(), nullable=True),
    sa.Column('alcohol_drug_use', sa.TEXT(), nullable=True),
    sa.Column('for_women_status', sa.TEXT(), nullable=True),
    sa.Column('chart_image_url', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['original_dr_uuid'], ['dentalrecord.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('dentalrecordsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalrecordsnapshot_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentalrecordsnapshot_snapshot_id'), ['snapshot_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_dentalrecordsnapshot_original_dr_uuid'), ['original_dr_uuid'], unique=False)

    op.create_table('personneltype',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('patient_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('personnel_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dl_uuid', sa.CHAR(length=32), nullable=True),
    sa.Column('teaching', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['dl_uuid'], ['departmentslookup.uuid'], ),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patientinformation.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('patient_uuid')
    )
    with op.batch_alter_table('personneltype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personneltype_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_personneltype_personnel_id'), ['personnel_id'], unique=1)

    op.create_table('patientfamilyhistory',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('pfh_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('mh_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mcl_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('family_relation', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['mcl_uuid'], ['medicalconditionslookup.uuid'], ),
    sa.ForeignKeyConstraint(['mh_uuid'], ['medicalhistory.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('patientfamilyhistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patientfamilyhistory_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_patientfamilyhistory_pfh_id'), ['pfh_id'], unique=1)

    op.create_table('medicalhistorysnapshot',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('original_mh_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('snapshot_date', sa.DATETIME(), nullable=False),
    sa.Column('smoking_status', sa.VARCHAR(length=13), nullable=False),
    sa.Column('smoking_started_since', sa.DATE(), nullable=True),
    sa.Column('drug_status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('drug_name', sa.VARCHAR(), nullable=True),
    sa.Column('did_rehab', sa.BOOLEAN(), nullable=True),
    sa.Column('alcohol_status', sa.VARCHAR(length=21), nullable=False),
    sa.Column('alcohol_est_consumption', sa.VARCHAR(), nullable=True),
    sa.Column('no_of_pregnancies', sa.INTEGER(), nullable=True),
    sa.Column('no_of_miscarriages', sa.INTEGER(), nullable=True),
    sa.Column('no_of_term_deliveries', sa.INTEGER(), nullable=True),
    sa.Column('no_of_premature_deliveries', sa.INTEGER(), nullable=True),
    sa.Column('total_children', sa.INTEGER(), nullable=True),
    sa.Column('surgery_notes', sa.TEXT(), nullable=True),
    sa.Column('maintenance_medications', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['original_mh_uuid'], ['medicalhistory.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicalhistorysnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalhistorysnapshot_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicalhistorysnapshot_snapshot_id'), ['snapshot_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_medicalhistorysnapshot_original_mh_uuid'), ['original_mh_uuid'], unique=False)

    op.create_table('medicalexamination',
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('me_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('mh_uuid', sa.CHAR(length=32), nullable=False),
    sa.Column('date_taken', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['mh_uuid'], ['medicalhistory.uuid'], ),
    sa.ForeignKeyConstraint(['patient_uuid'], ['patientinformation.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicalexamination', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalexamination_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicalexamination_patient_uuid'), ['patient_uuid'], unique=1)
        batch_op.create_index(batch_op.f('ix_medicalexamination_me_id'), ['me_id'], unique=1)

    # ### end Alembic commands ###
