"""added patient's family history of medical records

Revision ID: 38ffdbd4e577
Revises: fcacca582957
Create Date: 2026-03-11 23:49:02.104731

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38ffdbd4e577'
down_revision: Union[str, Sequence[str], None] = 'fcacca582957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patientfamilyhistory',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('pfh_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mh_uuid', sa.Uuid(), nullable=False),
    sa.Column('mcl_uuid', sa.Uuid(), nullable=False),
    sa.Column('family_relation', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['mcl_uuid'], ['medicalconditionslookup.uuid'], ),
    sa.ForeignKeyConstraint(['mh_uuid'], ['medicalhistory.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('patientfamilyhistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patientfamilyhistory_pfh_id'), ['pfh_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_patientfamilyhistory_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patientfamilyhistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patientfamilyhistory_uuid'))
        batch_op.drop_index(batch_op.f('ix_patientfamilyhistory_pfh_id'))

    op.drop_table('patientfamilyhistory')
    # ### end Alembic commands ###
