"""enforcing 1-to-1 relationship from medical and dental tables to patients

Revision ID: 80a71184b177
Revises: eee2569de4a9
Create Date: 2026-03-11 16:53:58.737798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80a71184b177'
down_revision: Union[str, Sequence[str], None] = 'eee2569de4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentalrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalrecord_patient_uuid'), ['patient_uuid'], unique=True)

    with op.batch_alter_table('medicalhistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalhistory_patient_uuid'))
        batch_op.create_index(batch_op.f('ix_medicalhistory_patient_uuid'), ['patient_uuid'], unique=True)

    with op.batch_alter_table('medicalhistoryupdate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalhistoryupdate_patient_uuid'), ['patient_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicalhistoryupdate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalhistoryupdate_patient_uuid'))

    with op.batch_alter_table('medicalhistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalhistory_patient_uuid'))
        batch_op.create_index(batch_op.f('ix_medicalhistory_patient_uuid'), ['patient_uuid'], unique=False)

    with op.batch_alter_table('dentalrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalrecord_patient_uuid'))

    # ### end Alembic commands ###
