"""added medical treatment table

Revision ID: c0e345221317
Revises: b8615a344dab
Create Date: 2026-03-11 21:18:33.608833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0e345221317'
down_revision: Union[str, Sequence[str], None] = 'b8615a344dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicaltreatment',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('mt_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mh_uuid', sa.Uuid(), nullable=False),
    sa.Column('date_taken', sa.Date(), nullable=False),
    sa.Column('physician_notes', sa.TEXT(), nullable=True),
    sa.Column('nurse_notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['mh_uuid'], ['medicalhistory.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicaltreatment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicaltreatment_mt_id'), ['mt_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicaltreatment_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicaltreatment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicaltreatment_uuid'))
        batch_op.drop_index(batch_op.f('ix_medicaltreatment_mt_id'))

    op.drop_table('medicaltreatment')
    # ### end Alembic commands ###
