"""creating snapshot tables

Revision ID: e091417b725f
Revises: 1708d943880e
Create Date: 2026-03-11 17:18:48.779591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e091417b725f'
down_revision: Union[str, Sequence[str], None] = '1708d943880e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicalhistorysnapshot',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('original_mh_uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('smoking_status', sa.Enum('NEVER', 'TRIED_ONCE', 'STOPPED_SINCE', 'ACTIVE', name='smokestatus'), nullable=False),
    sa.Column('smoking_started_since', sa.Date(), nullable=True),
    sa.Column('drug_status', sa.Enum('NEVER', 'TRIED_ONCE', 'SOMETIMES', 'ACTIVE', name='drugstatus'), nullable=False),
    sa.Column('drug_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('did_rehab', sa.Boolean(), nullable=True),
    sa.Column('alcohol_status', sa.Enum('NEVER', 'ONCE_A_WEEK', 'MORE_THAN_ONCE_A_WEEK', name='alcoholstatus'), nullable=False),
    sa.Column('alcohol_est_consumption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('no_of_pregnancies', sa.Integer(), nullable=True),
    sa.Column('no_of_miscarriages', sa.Integer(), nullable=True),
    sa.Column('no_of_term_deliveries', sa.Integer(), nullable=True),
    sa.Column('no_of_premature_deliveries', sa.Integer(), nullable=True),
    sa.Column('total_children', sa.Integer(), nullable=True),
    sa.Column('surgery_notes', sa.TEXT(), nullable=True),
    sa.Column('maintenance_medications', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['original_mh_uuid'], ['medicalhistory.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicalhistorysnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalhistorysnapshot_original_mh_uuid'), ['original_mh_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicalhistorysnapshot_snapshot_id'), ['snapshot_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicalhistorysnapshot_uuid'), ['uuid'], unique=False)

    op.create_table('dentalrecordsnapshot',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('original_dr_uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('last_dental_visit', sa.Date(), nullable=True),
    sa.Column('reason_for_last_dental_visit', sa.TEXT(), nullable=True),
    sa.Column('last_hospitalization', sa.Date(), nullable=True),
    sa.Column('hospitalization_reason', sa.TEXT(), nullable=True),
    sa.Column('known_allergies', sa.TEXT(), nullable=True),
    sa.Column('tobacco_use', sa.TEXT(), nullable=True),
    sa.Column('alcohol_drug_use', sa.TEXT(), nullable=True),
    sa.Column('for_women_status', sa.TEXT(), nullable=True),
    sa.Column('chart_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['original_dr_uuid'], ['dentalrecord.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('dentalrecordsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalrecordsnapshot_original_dr_uuid'), ['original_dr_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentalrecordsnapshot_snapshot_id'), ['snapshot_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_dentalrecordsnapshot_uuid'), ['uuid'], unique=False)

    op.create_table('medicalexaminationsnapshot',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('original_mhu_uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('date_taken', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['original_mhu_uuid'], ['medicalhistoryupdate.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('medicalexaminationsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicalexaminationsnapshot_original_mhu_uuid'), ['original_mhu_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicalexaminationsnapshot_snapshot_id'), ['snapshot_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicalexaminationsnapshot_uuid'), ['uuid'], unique=False)

    op.create_table('dentalexaminationsnapshot',
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('original_dr_uuid', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('examination_date', sa.Date(), nullable=False),
    sa.Column('head_findings', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('face_findings', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tmj_findings', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('periodontal_diagnosis', sa.Enum('HEALTHY', 'GINGIVITIS_LOCALIZED', 'GINGIVITIS_GENERALIZED', 'PERIODONTITIS_LOCALIZED', 'PERIODONTITIS_GENERALIZED', 'OTHERS', name='periodontaldiagnosis'), nullable=True),
    sa.Column('periodontitis_severity', sa.Enum('SLIGHT', 'MODERATE', 'SEVERE', name='severitytype'), nullable=True),
    sa.Column('periodontal_others', sa.TEXT(), nullable=True),
    sa.Column('lips_findings', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('palate_findings', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('floor_of_mouth_findings', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tongue_findings', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['original_dr_uuid'], ['dentalrecordupdate.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('dentalexaminationsnapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dentalexaminationsnapshot_original_dr_uuid'), ['original_dr_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_dentalexaminationsnapshot_snapshot_id'), ['snapshot_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_dentalexaminationsnapshot_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dentalexaminationsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalexaminationsnapshot_uuid'))
        batch_op.drop_index(batch_op.f('ix_dentalexaminationsnapshot_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_dentalexaminationsnapshot_original_dr_uuid'))

    op.drop_table('dentalexaminationsnapshot')
    with op.batch_alter_table('medicalexaminationsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalexaminationsnapshot_uuid'))
        batch_op.drop_index(batch_op.f('ix_medicalexaminationsnapshot_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_medicalexaminationsnapshot_original_mhu_uuid'))

    op.drop_table('medicalexaminationsnapshot')
    with op.batch_alter_table('dentalrecordsnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dentalrecordsnapshot_uuid'))
        batch_op.drop_index(batch_op.f('ix_dentalrecordsnapshot_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_dentalrecordsnapshot_original_dr_uuid'))

    op.drop_table('dentalrecordsnapshot')
    with op.batch_alter_table('medicalhistorysnapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicalhistorysnapshot_uuid'))
        batch_op.drop_index(batch_op.f('ix_medicalhistorysnapshot_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_medicalhistorysnapshot_original_mh_uuid'))

    op.drop_table('medicalhistorysnapshot')
    # ### end Alembic commands ###
