"""made patient_uuid unique in emergency contacts

Revision ID: fcacca582957
Revises: c0e345221317
Create Date: 2026-03-11 21:59:49.890562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fcacca582957'
down_revision: Union[str, Sequence[str], None] = 'c0e345221317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergencycontact', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_emergencycontact_patient_uuid', ['patient_uuid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergencycontact', schema=None) as batch_op:
        batch_op.drop_constraint('uq_emergencycontact_patient_uuid', type_='unique')

    # ### end Alembic commands ###
